[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm db:generate"

[deploy]
startCommand = "pnpm --filter @son1kvers3/backend start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
